### PR TITLE
Swift 3.1 on macOS

### LINKED ISSUE #348: Support Swift 3.1
Or else I'm compiling something wrong.

This is my environment:
* **OS:** Linux, Elementary OS (based on Ubuntu 16.04 LTS)
* **Toolchain:** Swift version 3.1-dev (LLVM a7c680da51, Clang 9772bf511a, Swift ac7b7f3777)

I compiled the toolchain myself.

And this is how I tried to compile SourceKitten:
1. **Ran this**:
```sh
sudo echo >> ~/.bashrc
sudo echo export LINUX_SOURCEKIT_LIB_PATH='/build/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-03-19-a/usr/lib/sourcekitdInProc.framework/sourcekitdInProc' >> ~/.bashrc
```
2. **Relaunched the Terminal, cloned the repo and checkout-ed the latest release**:
```sh
git clone https://github.com/jpsim/SourceKitten
cd SourceKitten/
git checkout tags/0.17.0
```
3. **Tried to build it** (here it failed)
```console
$ swift build
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/norio-nomura/Clang_C.git
Fetching https://github.com/norio-nomura/SourceKit.git
Fetching https://github.com/antitypical/Result.git
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 3.2.1
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 3.0.3
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at 0.11.3
Cloning https://github.com/norio-nomura/SourceKit.git
Resolving https://github.com/norio-nomura/SourceKit.git at 1.0.1
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 0.1.4
Cloning https://github.com/norio-nomura/Clang_C.git
Resolving https://github.com/norio-nomura/Clang_C.git at 1.0.2
error: the package has an unsupported layout, modulemap (/home/felix/Desktop/other-scripts/SourceKitten/Source/SourceKittenFramework/clang-c/module.modulemap) is not allowed to be mixed with sources
fix: move the modulemap inside include directory
```
I think either I did some step wrong, compiled or configured the Swift toolchain badly, or SourceKitten doesn't support Swift 3.1 yet :thinking:

### PR DESCRIPTION
**Pull request by norio-nomura**
fixes #348 
Todo:
- [x] Fix tests for Xcode
- [x] Fix tests for SwiftPM  
  checkout path has been changed by SwiftPM
- ~[ ] Fix tests for Linux~  
- [x] Update Yams to coming release

### CODE REVIEW

**Comment by norio-nomura** [comment]
It seems all `source.request.editor.open` request fails on Linux with following error:
> SOURCEKITD FATAL ERROR: sourcekitd object did not resolve to a known type

😞

File: Tests/SourceKittenFrameworkTests/ModuleTests.swift [hunk 1]
```diff
@@ -48,9 +48,31 @@ class ModuleTests: XCTestCase {
 #if SWIFT_PACKAGE
 extension ModuleTests {
     func testCommandantDocsSPM() {
-        let commandantPath = projectRoot + "/Packages/Commandant-0.11.3/"
+    #if swift(>=3.1) && os(Linux)
+        // FIXME
+        print("FIXME: Skip \(#function), because our sourcekitInProc on Swift 3.1 for Linux seems to be broken")
+    #else
+        func findCommandant(in directory: String) -> String? {
```
Comment (jpsim) [inline Tests/SourceKittenFrameworkTests/ModuleTests.swift]: It's a shame `swift build --get-package-path Commandant` (from [SE-0082](https://github.com/apple/swift-evolution/blob/master/proposals/0082-swiftpm-package-edit.md#detailed-design)) doesn't appear to work yet 🤔

**Comment by jpsim** [comment]
Big thanks for this @norio-nomura! Those `key.actionable` entries look promising!

File: Tests/SourceKittenFrameworkTests/ModuleTests.swift (hunk 1 above)
Comment (norio-nomura) [inline Tests/SourceKittenFrameworkTests/ModuleTests.swift]: I got response in http://swiftpm.slack.com that parsing `swift package show-dependencies --format json` is one way to solve it.
In the long run, it may be good to use `libSwiftPM` including this too.
