### PR TITLE
fix bug where parsed declaration would include body

### LINKED ISSUE #45: Don't include body in parsed_declaration
This typically happens right now when the body starts on one of the lines used by the declaration.

### PR DESCRIPTION
**Pull request by jpsim**
fixes #45

### CODE REVIEW

File: Source/SourceKittenFramework/File.swift [hunk 1]
```diff
@@ -100,10 +100,12 @@ public final class File {
             return nil
         }
         return SwiftDocKey.getOffset(dictionary).flatMap { start in
-            let end = SwiftDocKey.getBodyOffset(dictionary).map { Int($0) }
             let start = Int(start)
-            let length = (end ?? start) - start
-            return contents.substringLinesWithByteRange(start: start, length: length)?
+            if let end = SwiftDocKey.getBodyOffset(dictionary).map({ Int($0) }) {
+                return contents.substringStartingLinesWithByteRange(start: start, length: (end ?? start) - start)?
```
Comment (norio-nomura) [inline Source/SourceKittenFramework/File.swift]: `end` is already unwrapped here.

Comment (jpsim) [inline Source/SourceKittenFramework/File.swift]: Nice catch. Thank you!

File: sourcekitten.xcodeproj/xcshareddata/xcschemes/sourcekitten.xcscheme [hunk 2]
```diff
@@ -17,7 +17,7 @@
                BlueprintIdentifier = "D0E7B63119E9C64500EDBA4D"
                BuildableName = "sourcekitten.app"
                BlueprintName = "sourcekitten"
-               ReferencedContainer = "container:sourcekitten.xcodeproj">
+               ReferencedContainer = "container:SourceKitten.xcodeproj">
```
Comment (norio-nomura) [inline sourcekitten.xcodeproj/xcshareddata/xcschemes/sourcekitten.xcscheme]: It seems `sourcekitten.xcodeproj` are mixed with `SourceKitten.xcodeproj`.
Directory name is `sourcekitten.xcodeproj`, but `sourcekitten.xcodeproj/project.pbxproj` thinks itself as `SourceKitten.xcodeproj`.
