### PR TITLE
Fix the trimming of trailing characters.

### LINKED ISSUE #350: SourceKitten crashes when a documentation comment ends with an extended grapheme cluster.
NSString and Swift's String handle extended grapheme clusters differently. While removing trailing whitespace, SourceKitten tries to create a UnicodeScalar from an NSString character which does not necessarily succeed. Because of that SourceKitten crashes at force-unwrapping the unicode scalar (`String+SourceKitten.swift`, line 241 in `trimmingTrailingCharacters(in characterSet: CharacterSet)`.

Minimal example:
```Swift
/**💣*/
class Foobar{
}
```

### PR DESCRIPTION
**Pull request by Lukas-Stuehrk**
When the string ended with extended grapheme clusters, the method
crashed because of the force-unwrapping. This refactoring adds support
for handling extended grapheme clusters.

This fixes #350

### CODE REVIEW

File: Source/SourceKittenFramework/String+SourceKitten.swift [hunk 1]
```diff
@@ -232,14 +232,15 @@ extension NSString {
...
         }
-        var charBuffer = [unichar](repeating: 0, count: length)
-        getCharacters(&charBuffer, range: NSRange(location: 0, length: charBuffer.count))
-        for newLength in (1...length).reversed() {
-            if !characterSet.contains(UnicodeScalar(charBuffer[newLength - 1])!) {
-                return substring(with: NSRange(location: 0, length: newLength))
+        var string = self.bridge()
+        let endIndex = string.unicodeScalars.endIndex
+        for offset in 1...string.unicodeScalars.count {
+            let index = string.unicodeScalars.index(endIndex, offsetBy: -offset)
```
Comment (norio-nomura) [inline Source/SourceKittenFramework/String+SourceKitten.swift]: This creates the index from the end of the string every time.
Can you reuse the index created in the previous loop to reduce computational cost?

Comment (Lukas-Stuehrk) [inline Source/SourceKittenFramework/String+SourceKitten.swift]: Yes, you're right. Thanks for the input. I think there's even a much easier implementation (at least for me it's much easier to wrap my head around 😉 ):
```Swift
        var unicodeScalars = self.bridge().unicodeScalars
        while let scalar = unicodeScalars.last {
            if !characterSet.contains(scalar) {
                return String(unicodeScalars)
            }
            unicodeScalars.removeLast()
        }
```

Do you have concerns?

Comment (jpsim) [inline Source/SourceKittenFramework/String+SourceKitten.swift]: Looks fine to me.

Comment (norio-nomura) [inline Source/SourceKittenFramework/String+SourceKitten.swift]: 👍

**Comment by norio-nomura** [comment]
Could you please add a changelog entry? Thanks!

**Comment by Lukas-Stuehrk** [comment]
Sure! Done.

**Comment by jpsim** [comment]
Thanks @Lukas-Stuehrk!

**Comment by Lukas-Stuehrk** [comment]
You're welcome. I'm happy to help on such a handy and important piece in the Swift tooling. Thanks for the fast reviews, good feedback and all your work.
